### ISSUE TITLE
Need to figure out why precision for PLIER is so much higher than autoPLIER in current tests

### ISSUE THREAD

**Issue by millerh1** [Bishop-Laboratory/autoPLIER-analysis#38]
The precision for autoPLIER appears to be much lower than PLIER on the CELLO dataset.

1. Is the reconstruction error correlated with the classification error?
2. Is autoPLIER mis-classifying the same labels as PLIER?
3. If you remove the label with the low number of samples, does it improve the performance?
4. Can you add the standard deviation to the plots?

**Comment by millerh1** [comment]
We also decided that the Z matrix from PLIER is probably not very sparse... We should analyze the sparsity of Z and target that sparsity with autoPLIER. That may improve autoPLIER performance compared to PLIER.

**Comment by Julian-Borbeck** [comment]
PLIER is not true NMF, the embedding contains negative values.
